name: CD
on:
  push:
    branches:
      - webpage-master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Redeploy docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull mleon96/${{ secrets.DOCKER_REPOSITORY }}
            docker container stop docker-deploy
            docker container rm docker-deploy
            docker run --name docker-deploy -d -p 80:80 mleon96/${{ secrets.DOCKER_REPOSITORY }}
            docker logout