name: CI
on:
  push:
    branches: ['develop']
env:
  STATE_RELEASE_VERSION: 1.0.0
jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout


      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "0.99.1"

      - name: Build Html Website
        run: hugo -D

      - name: Test Html Build with HTMLPROOFER
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: "./public"
          # The directory to scan
          arguments: --allow-missing-href --disable-external --empty-alt-ignore 

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Publish to Registry
        pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: mleon96/week-4
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.STATE_RELEASE_VERSION }}"

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "👑 *An automated PR*"
          pr_reviewer: "mdeleon"
          pr_draft: true
          github_token: ${{ secrets.TOKEN_REPOSITORY }}