name: CI
on:
  push:
    branches: ["webpage-develop"]
env:
  STATE_RELEASE_VERSION: 0.0.1
jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "0.99.1"

      - name: Build Html Website
        run: hugo -D

      - name: Test Html Build with HTMLPROOFER
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: "./public"
          arguments: --allow_missing_href --disable_external --ignore_empty_alt

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: mleon96/${{ secrets.DOCKER_REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
          dockerfile: ./docker-resources/Dockerfile

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "webpage-master"
          pr_title: "Pulling ${{ github.ref }} into webpage-master"
          pr_body: "👑 *An automated PR*"
          pr_reviewer: "mdeleon"
          pr_draft: true
          github_token: ${{ secrets.TOKEN_REPOSITORY }}
